### ISSUE TITLE
about timer

### ISSUE THREAD

**Issue by wangyuntao** [jurmous/etcd4j#105]
Hi @lburgazzoli, i saw your recent commit "Attempt to fix #95, update dependencies"  change something about timer, but i have some questions:

1)  You create a new timer in EtcdNettyClient, and reference the timer in ConnectionState, i guess you want to use this timer in RetryPolicy.retry method, but that method still use the static timer, is it wrong?

2) In RetryPolicy.retry method, when test the request should not retry, you close the timer (no matter which one you want to close), but this is just a request, the timer need to serve all requests, is it wrong?

Thanks!

**Comment by lburgazzoli** [comment]
yes it is definitively my mistake, the one held by connection state should be used, would you like to submit a PR ?

**Comment by wangyuntao** [comment]
I suggest that set timer thread to daemon, so when all threads close, the timer thread close also, how do you think?

**Comment by wangyuntao** [comment]
And #95 is fixed also.

**Comment by wangyuntao** [comment]
Or let user provide a timer in constructor, if not provided, EtcdNettyClient create a new one, and the timer thread is daemon.

**Comment by wangyuntao** [comment]
I think this method is better!

**Comment by lburgazzoli** [comment]
yep, latest one looks good to mee

**Comment by wangyuntao** [comment]
ok, i'll submit a PR later.

**Comment by wangyuntao** [comment]
Hi @lburgazzoli , a new PR done, about timer and other bugfix!

**Comment by wangyuntao** [comment]
Check the new PR, thanks!

**Comment by lburgazzoli** [comment]
PR merged, thx
