### ISSUE TITLE
Etcd requests are not properly canceled after client close.

### ISSUE THREAD

**Issue by jurmous** [jurmous/etcd4j#107]
Test testIfCleanClose fails when run together with other tests. The response resolvement should send a CancelationException.

**Comment by lburgazzoli** [comment]
@jurmous is that fixed by your last commit ? Running the tests from gradle does not report any failure

**Comment by jurmous** [comment]
For me the testIfCleanClose runs ok when runned separately but not when they all run together. Then the test hangs...

**Comment by jurmous** [comment]
I can look into it this weekend. If anyone can fix it earlier it would be great.

**Comment by lburgazzoli** [comment]
@jurmous please have a look at my latest commit

**Comment by jurmous** [comment]
It worked! Thanks 😄
