### ISSUE TITLE
etcd APIv3 support

### ISSUE THREAD

**Issue by halacs** [jurmous/etcd4j#115]
It would be nice to support etcd API v3. Thanks.

**Comment by lburgazzoli** [comment]
I'm looking at v3 api but it may take a little time, any help would be really appreciated

**Comment by xiang90** [comment]
We are trying to collaborate on a v3 java implementation here: https://github.com/coreos/jetcd.

Any help would be highly appreciated!

**Comment by jurmous** [comment]
A http/2 and protobuf api would mean an almost complete rewrite of all code. We are currently opening a connection per request and it would mean we need to switch to a channel pooled implementation but that means a lot of assumptions need to be removed from the channel handlers. 

@xiang90 what are your plans with the new client and how could we help?

I would then prefer to support this new coreos backed api and apply the learned lessons here to that new client.

**Comment by lburgazzoli** [comment]
@jurmous agree making etcd4j v3 ready would be an huge effort so working on an "official" java client is the way to go imho

**Comment by xiang90** [comment]
@jurmous 

The v3 client in coreos repo is a community effort. I am trying to coordinate people, and help on the interface design (to make it not super diverged from the go impl) and answer questions. My hope is to have 1 feature completed, general purpose java client with better community support.

I am going to write about some things we learned from go client implementation and some implementation considerations over the weekend.

**Comment by lburgazzoli** [comment]
v3 API will be implemented in https://github.com/coreos/jetcd
