### ISSUE TITLE
i update version to 2.12.0 my programmer has been blocked

### ISSUE THREAD

**Issue by dragontree101** [jurmous/etcd4j#116]
i update version to 2.12.0 my programmer has been blocked
my code is  ```client.version()```  and etcd will be blocked。

i debug code found it blocked in ```listeningPromise.awaitUninterruptibly();```

**Comment by jurmous** [comment]
version() is (one of) the only blocking calls in etcd4j. It does not return a promise but a String. I for now forgot the reason but probably for convenience. If you must have it in a non blocking way:

new EtcdVersionRequest(etcdClient, retryHandler).send()

**Comment by dragontree101** [comment]
i use other method also will be blocked, i use 2.11.0 does not this problem,  i don't what change will cause this block?

**Comment by lburgazzoli** [comment]
I've tested it and it does not fail, which etcd version are you on ?

**Comment by abarsov** [comment]
The same issue with 2.12.0.
I deployed etcd cluster (using docker image: quay.io/coreos/etcd:v2.3.0)

Link 
http://localhost:2579/version 
returns in browser
{"etcdserver":"2.3.0","etcdcluster":"2.3.0"}

The following code hangs forever on listeningPromise.awaitUninterruptibly();
try (EtcdClient etcd = new EtcdClient(URI.create("http://localhost:2379"), URI.create("http://localhost:2479"), URI.create("http://localhost:2579"))){
      System.out.println(etcd.version().getCluster());
    } catch (IOException e) {
      e.printStackTrace();
    }

(It hangs the same way if I created client as new EtcdClient(URI.create("http://localhost:2379")).

**Comment by lburgazzoli** [comment]
I think this is linked to netty dns resolver issue (https://github.com/netty/netty/issues/5386), could you give it a try by setting the ip address instead of localhost ?

**Comment by sheinbergon** [comment]
@jurmous @lburgazzoli  in 2.12.0 you've an issue in https://github.com/jurmous/etcd4j/blob/release-2.11.0/src/main/java/mousio/client/promises/ResponsePromise.java inside the method    

```
protected boolean waitForPromiseSuccess() throws IOException, TimeoutException {
    if (!promise.isDone() && !promise.isCancelled()) {
      Promise<T> listeningPromise = this.promise;
      listeningPromise.awaitUninterruptibly();
      if (listeningPromise != this.promise) {
        return false;
      }
      this.handlePromise(promise);
    }
    return true;
  }
```

for some reason , in version 2.12.0 ( probably related due to the fact you upgraded the netty version to 4.1.3 )  the promise never reaches the 'done' state ( the Future never signals it's in a 'done' state )
so it enters the awaitUninterruptibly() but as the response was already sent , no response is sent again on the connection and basically - nothing ever happens , so the thread just keeps waiting forever.

inside Netty's 'DefaultPromise' class

the following method never returns true :
```
private static boolean isDone0(Object result) {
        return result != null && result != UNCANCELLABLE;
 }
```

Running tcpdump on the etcd shows it returns  a valid version response , so without going further into the code.I also have a gut feeling this is an async-related issue , that takes place when response returns too quickly and the client code misses the event

**Comment by alexlee85** [comment]
same issue with 2.12. never return result.
if I add a timeout on EtcdKeyGetRequest, it always timeout.

**Comment by lburgazzoli** [comment]
Any chance to test against the latest code which depends on netty 4.1.4 ?

I'm unable to reproduce in my env

**Comment by doanduyhai** [comment]
Same issue for me using version 2.12.0. It was working with previous version 2.11.0. 

Same analysis as @sheinbergon, the code blocks at `listeningPromise.awaitUninterruptibly();` 

It's a pitty, I have to use Netty 4.3.1.Final, look like I need to choose another client :(

**Comment by lburgazzoli** [comment]
@sheinbergon thx for the detail, however I'm unable to reproduce it :( 

Would you be so kind to test against the latest code in which we have bumped netty version to v 4.1.4 ?

**Comment by sheinbergon** [comment]
@lburgazzoli  I will test with the new version and let you know in a matter of a few days

**Comment by tsl0922** [comment]
Same here using version 2.12.0, version() blocks forever, but getVersion() works, this is part of the version() call's debug log:

```
14:07:21.338 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
14:07:21.338 [nioEventLoopGroup-2-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@7b8cae58
14:07:21.372 [nioEventLoopGroup-2-1] DEBUG io.netty.resolver.dns.DnsNameResolver - -Djava.net.preferIPv6Addresses: false
14:07:21.396 [nioEventLoopGroup-2-1] DEBUG mousio.etcd4j.transport.EtcdNettyClient - Connected to /127.0.0.1:2379 (0)
14:07:21.403 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity: 262144
14:07:21.403 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
14:07:21.403 [nioEventLoopGroup-2-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
14:07:21.436 [nioEventLoopGroup-2-1] DEBUG mousio.etcd4j.transport.EtcdResponseHandler - Received 200 for GET /version
```

**Comment by lburgazzoli** [comment]
@tsl0922 Are you able to debug EtcdResponseHandler::channelRead0 ?

**Comment by dragontree101** [comment]
@lburgazzoli I'm sorry for being late
describe my env:
my etcd install in localhost, version is 3.0. 
etcd4j version is 2.12.0 and uri list is ```http://127.0.0.1:2379```
netty has lot of
```
[INFO] |  |  \- org.mousio:etcd4j:jar:2.12.0:compile
[INFO] |  |     +- io.netty:netty-codec-dns:jar:4.1.3.Final:compile
[INFO] |  |     +- io.netty:netty-resolver-dns:jar:4.1.3.Final:compile
.....
[INFO] |  |  +- io.reactivex:rxnetty:jar:0.4.9:runtime
[INFO] |  |  |  \- io.netty:netty-transport-native-epoll:jar:4.0.27.Final:runtime
......
[INFO] |  +- com.netflix.ribbon:ribbon-transport:jar:2.2.0:compile
[INFO] |  |  +- io.reactivex:rxnetty-contexts:jar:0.4.9:runtime
[INFO] |  |  \- io.reactivex:rxnetty-servo:jar:0.4.9:runtime
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.0.CR7:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.0.CR7:compile
[INFO] |  \- io.netty:netty-handler:jar:4.1.0.CR7:compile
[INFO] |     +- io.netty:netty-buffer:jar:4.1.0.CR7:compile
[INFO] |     |  \- io.netty:netty-common:jar:4.1.0.CR7:compile
[INFO] |     \- io.netty:netty-transport:jar:4.1.0.CR7:compile
[INFO] |        \- io.netty:netty-resolver:jar:4.1.0.CR7:compile
.......
[INFO] |  |  |  |  \- org.apache.zookeeper:zookeeper:jar:3.4.6:compile
[INFO] |  |  |  |     +- jline:jline:jar:0.9.94:compile
[INFO] |  |  |  |     \- io.netty:netty:jar:3.7.0.Final:compile
```

and i can debug ```EtcdResponseHandler::channelRead0```  
and what should i do?

**Comment by lburgazzoli** [comment]
@dragontree101 

1. etcd4j uses jackson 2.8.0
2. I see lot of netty deps, it would be nice not to to mix them
3. I would like to see if channelRead0 notifies the promises or not.

**Comment by dragontree101** [comment]
my project dependency a lot jar,  i think maybe this problem because of jackson's version
my project dependency spring-cloud-config-client, and spring-cloud-config-client use jackson version is 2.6.7,   and in jackson 2.6.7 not this method ```MAPPER.readValue(di, this.type);```   type error, i think this method add in jackson 2.8.0+,  and i force use jackson 2.8.0+  but ```spring-cloud-config-client``` startup error :(

**Comment by dragontree101** [comment]
@lburgazzoli  i update my spring-boot version to 1.4.0.RELEASE， and jackson version update to 2.8.1,  and then everything is ok.

**Comment by lburgazzoli** [comment]
Do you mean it does not block anymore ?

**Comment by dragontree101** [comment]
yes ,  i think  because of jackson version's problem
in jackson 2.6.7 verison not ```MAPPER.readValue(di, this.type)``` method
and spring-boot-1.3.6.RELEASE use jackson 2.6.7  so  ```MAPPER.readValue(di, this.type)``` throw exception, and netty likes always in ````while(true) {...}```

**Comment by tsl0922** [comment]
Hi @lburgazzoli

I'm using spring-boot 1.3.5 RELEASE, update to 1.4.0.RELEASE solved this issue, too.

**Comment by dragontree101** [comment]
@tsl0922  en , spring-boot 1.4.0 update jackson 2.6.7 to 2.8.1, so no exception anymore.

**Comment by idans-ybrantdigital-com** [comment]
Hi guys.

This issue ( which also affects watchers ) does not happen in 2.11.0 but does happen in 2.12.0. 
Any plan to release a new version ( 2.1.13 to maven  ) any time soon

**Comment by sheinbergon** [comment]
Hi guys.

This issue ( which also affects watchers ) does not happen in 2.11.0 but does happen in 2.12.0. 
Any plan to release a new version ( 2.1.13 to maven ) any time soon
