### ISSUE TITLE
Support for setting watchers

### ISSUE THREAD

**Issue by hariav** [jurmous/etcd4j#118]
Could not find  a way to set watch for a key. Is this a missing feature in java client?

**Comment by hariav** [comment]
Just went through the issues and got this "waitForChange". Let me try this

**Comment by hariav** [comment]
Gone through [EtcdWatchConsumer.java](https://github.com/apache/camel/blob/master/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java) as well. If I have to continuously watch for any changes, is this a good way? There are chances of loosing some changes, while I do the change processing right?

**Comment by lburgazzoli** [comment]
As long as you provide the right index you should not loose any event

**Comment by hariav** [comment]
Yes.. key is to wait on index, rather than wait on key. Thanks. 
It would be great to abstract this out in the library and provide simple interface which can be used to wait and iterate on events. Similar to the one in go driver. I can try to submit the change if this looks like a good option. 

public ChangeEvent next() ;

**Comment by lburgazzoli** [comment]
Please go ahead ;)

**Comment by lburgazzoli** [comment]
@hariav any progress ?

**Comment by lburgazzoli** [comment]
Closed as no feedback from reporter
