### ISSUE TITLE
Infinite loop when the etcd server has a DNS resolve problem

### ISSUE THREAD

**Issue by bladehd** [jurmous/etcd4j#127]
When I invoke EtcdResponsePromise.get() method, if the etcd server has a dns resolve problem, it will has a infinite loop.
I think etcd4j need add a timeout for get method.
etcd4j version 2.12.0.

**Comment by lburgazzoli** [comment]
etcd4j has a retry handler, doesn't it work for you ?

**Comment by sheinbergon** [comment]
etcd4j version 2.12.0 . Try this again with 2.11.0

**Comment by lburgazzoli** [comment]
Closed as no feedback from the reporter
