### ISSUE TITLE
Got exception when use etcd4j in karaf 3.0.5

### ISSUE THREAD

**Issue by bobzhouHW** [jurmous/etcd4j#129]
I got a exception when i try to use etcd4j in karaf 3.0.5 to get etcd data. The exception is as below.

com.fasterxml.jackson.databind.JsonMappingException: Failed to load class 'mousio.etcd4j.responses.EtcdKeysResponse$Access4JacksonDeserializerba7d7b73': com.fasterxml.jackson.module.afterburner.deser.BeanPropertyMutator
 at [Source: io.netty.buffer.ByteBufInputStream@4071d7e0; line: 1, column: -1]

And fellow http://stackoverflow.com/questions/37219960/karaf-not-able-to-load-afterburner-classes-during-runtime. I have add "<Import-Package>com.fasterxml.jackson.databind.ser,com.fasterxml.jackson.databind.deser,com.fasterxml.jackson.databind.ser.std,com.fasterxml.jackson.databind.deser.std,com.fasterxml.jackson.module.afterburner.ser,com.fasterxml.jackson.module.afterburner.deser,*</Import-Package>" in pom.xml. But it's not work.

**Comment by bobzhouHW** [comment]
The version of etcd4j is 2.12

**Comment by lburgazzoli** [comment]
Can you show what bundles you have installed ?

**Comment by bobzhouHW** [comment]
@lburgazzoli 
Here is my bundle details.

onos> bundle:headers 195

onos-app-evpn (195)
-------------------
Service-Component = OSGI-INF/org.onosproject.evpn.manager.impl.EvpnManager.xml,OSGI-INF/org.onosproject.evpn.rsc.baseport.impl.BasePortManager.xml,OSGI-INF/org.onosproject.evpn.rsc.vpnport.impl.VpnPortManager.xml,OSGI-INF/org.onosproject.evpn.rsc.vpninstance.impl.VpnInstanceManager.xml
Created-By = Apache Maven Bundle Plugin
Manifest-Version = 1.0
Bnd-LastModified = 1477645902040
Build-Jdk = 1.8.0_65
Built-By = onos
Tool = Bnd-2.1.0.20130426-122213

Bundle-Blueprint = OSGI-INF/blueprint/shell-config.xml
Bundle-License = http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-ManifestVersion = 2
Bundle-SymbolicName = org.onosproject.onos-app-evpn
Bundle-Version = 1.8.0.SNAPSHOT
Bundle-Name = onos-app-evpn
Bundle-Description = ONOS EVPN application

Export-Package = 
	org.onosproject.evpn.manager;uses:="org.onosproject.incubator.net.evpnrouting,org.onosproject.net";version=1.8.0,
	org.onosproject.evpn.rsc.cli;uses:="org.apache.karaf.shell.commands,org.onosproject.cli";version=1.8.0,
	org.onosproject.evpn.rsc;uses:="org.onlab.util,org.onosproject.incubator.net.evpnprivaterouting,org.onosproject.incubator.net.evpnrouting";version=1.8.0,
	org.onosproject.evpn.rsc.vpninstance;uses:="com.justinsb.etcd,org.onosproject.evpn.rsc";version=1.8.0,
	org.onosproject.evpn.rsc.vpnport;uses:="com.justinsb.etcd,org.onosproject.event,org.onosproject.evpn.rsc";version=1.8.0,
	org.onosproject.evpn.rsc.baseport;uses:="com.justinsb.etcd,org.onlab.packet,org.onosproject.net,org.onosproject.vtnrsc";version=1.8.0,
	com.justinsb.etcd;uses:="com.google.common.util.concurrent,org.apache.http,org.apache.http.client.methods";version=1.8.0
Import-Package = 
	com.fasterxml.jackson.databind;version="[2.7,3)",
	com.google.common.base;version="[19.0,20)",
	com.google.common.collect;version="[19.0,20)",
	com.google.common.util.concurrent;version="[19.0,20)",
	com.google.gson;version="[2.7,3)",
	com.justinsb.etcd;version="[1.8,2)",
	mousio.etcd4j;version="[2.12,3)",
	mousio.etcd4j.promises;version="[2.12,3)",
	mousio.etcd4j.requests;version="[2.12,3)",
	mousio.etcd4j.responses;version="[2.12,3)",
	org.apache.http,
	org.apache.http.client.config,
	org.apache.http.client.entity,
	org.apache.http.client.methods,
	org.apache.http.concurrent,
	org.apache.http.impl.nio.client;version="[4.1,5)",
	org.apache.http.message,
	org.apache.http.util,
	org.apache.karaf.shell.commands;version="[3.0,4)",
	org.onlab.packet;version="[1.8,2)",
	org.onlab.util;version="[1.8,2)",
	org.onosproject.cli;version="[1.8,2)",
	org.onosproject.core;version="[1.8,2)",
	org.onosproject.event;version="[1.8,2)",
	org.onosproject.evpn.manager;version="[1.8,2)",
	org.onosproject.evpn.rsc;version="[1.8,2)",
	org.onosproject.evpn.rsc.baseport;version="[1.8,2)",
	org.onosproject.evpn.rsc.vpninstance;version="[1.8,2)",
	org.onosproject.evpn.rsc.vpnport;version="[1.8,2)",
	org.onosproject.incubator.net.evpnprivaterouting;version="[1.8,2)",
	org.onosproject.incubator.net.evpnrouting;version="[1.8,2)",
	org.onosproject.incubator.net.resource.label;version="[1.8,2)",
	org.onosproject.mastership;version="[1.8,2)",
	org.onosproject.net;version="[1.8,2)",
	org.onosproject.net.behaviour;version="[1.8,2)",
	org.onosproject.net.device;version="[1.8,2)",
	org.onosproject.net.driver;version="[1.8,2)",
	org.onosproject.net.flow;version="[1.8,2)",
	org.onosproject.net.flow.instructions;version="[1.8,2)",
	org.onosproject.net.flowobjective;version="[1.8,2)",
	org.onosproject.net.host;version="[1.8,2)",
	org.onosproject.store;version="[1.8,2)",
	org.onosproject.store.serializers;version="[1.8,2)",
	org.onosproject.store.service;version="[1.8,2)",
	org.onosproject.vtn.util;version="[1.8,2)",
	org.onosproject.vtnrsc;version="[1.8,2)",
	org.onosproject.vtnrsc.virtualport;version="[1.8,2)",
	org.osgi.service.blueprint;version="[1.0.0,2.0.0)",
	org.slf4j;version="[1.7,2)",
	com.fasterxml.jackson.annotation;version="[2.7,3)",
	com.fasterxml.jackson.databind.ser.std;version="[2.7,3)",
	com.fasterxml.jackson.databind.deser;version="[2.7,3)",
	com.fasterxml.jackson.databind.annotation;version="[2.7,3)",
	com.fasterxml.jackson.module.afterburner.ser,
	com.fasterxml.jackson.module.afterburner.deser,
	com.fasterxml.jackson.databind.ser;version="[2.7,3)",
	com.fasterxml.jackson.databind.deser.std;version="[2.7,3)",
	com.fasterxml.jackson.core;version="[2.8,3)",
	com.fasterxml.jackson.module.afterburner;version="[2.8,3)"

**Comment by lburgazzoli** [comment]
I meant the bundle you have installed along with etcd4j (netty, jackson)

**Comment by bobzhouHW** [comment]
Here is my features.xml. I have install netty and jackson packages here.
<features xmlns="http://karaf.apache.org/xmlns/features/v1.2.0" name="${project.artifactId}-${project.version}">
    <feature name="${project.artifactId}" version="${project.version}"
             description="${project.description}">
        <feature>onos-api</feature>
        <bundle>mvn:${project.groupId}/onos-app-vtn-rsc/${project.version}</bundle>
        <bundle>mvn:${project.groupId}/onos-app-vtn-web/${project.version}</bundle>
        <bundle>mvn:${project.groupId}/onos-app-vtn-mgr/${project.version}</bundle>
        <bundle>mvn:${project.groupId}/onos-app-evpn/${project.version}</bundle>
        <bundle>mvn:com.google.code.gson/gson/2.7</bundle>
        <bundle>mvn:org.apache.httpcomponents/httpclient-osgi/4.4.1</bundle>
        <bundle>mvn:org.apache.httpcomponents/httpcore-osgi/4.4.4</bundle>
        <bundle>mvn:org.apache.httpcomponents/httpasyncclient-osgi/4.1.1</bundle>
        <bundle>mvn:com.fasterxml.jackson.core/jackson-annotations/2.8.0</bundle>
        <bundle>mvn:com.fasterxml.jackson.core/jackson-databind/2.8.0</bundle>
        <bundle>mvn:com.fasterxml.jackson.core/jackson-core/2.8.0</bundle>
        <bundle>mvn:com.fasterxml.jackson.module/jackson-module-afterburner/2.8.0</bundle>
        <bundle>mvn:io.netty/netty-codec-dns/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-resolver-dns/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-handler/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-codec-http/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-resolver/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-common/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-buffer/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-transport/4.1.3.Final</bundle>
        <bundle>mvn:io.netty/netty-codec/4.1.3.Final</bundle>
        <bundle>mvn:org.mousio/etcd4j/2.12.0</bundle>
    </feature>
</features>

**Comment by lburgazzoli** [comment]
Can you check with the latest code ? 
Btw, when doing gradle install it should also install the feature

**Comment by bobzhouHW** [comment]
@lburgazzoli 
Hi lburgazzoli. I have verified it with latest code. There is no error in karaf.
Thanks for helping.

**Comment by bobzhouHW** [comment]
@lburgazzoli 
Hi lburgazzoli. Can you help to update jar in maven repository ? One more question we wish to use etcd4j to monitor data change in remote etcd server. Now we use one watch request to monitor etcd. And once it got callback data. we will start a new monitor on it. In this way we will miss some data change between two monitor request. My question is is there a good way to continue watch the data change on etcd.

Thanks.

**Comment by jurmous** [comment]
2.13.0-SNAPSHOT is published. The final release is blocked by #131 at the moment. (I can't work on it unfortunately)

**Comment by bobzhouHW** [comment]
Got it. Thanks.

**Comment by lburgazzoli** [comment]
@bobzhouHW when you get the callback you also get the index you can use for the next watch, have a look at camel-etcd (can't provide a link at the moment)

**Comment by bobzhouHW** [comment]
@lburgazzoli Thanks for your advice.

**Comment by cmukunda** [comment]
Hi lburgazzoli, I got the same exception on Apache Felix. In my case, the version of etcd4j is 2.13.0
jackson version is 2.8.6, io.netty version is 4.1.7.Final.
