### ISSUE TITLE
Response doesn't receive

### ISSUE THREAD

**Issue by wojtkuju** [jurmous/etcd4j#136]
I'm using 2.13.0 version and I have code:
`SslContext sslContext = null;
        try {
            sslContext = SslContext.newClientContext();
        EtcdClient etcd = new EtcdClient(sslContext,
                URI.create("https://10.122.17.3:2379"));
            EtcdKeysResponse response = etcd.put("foo", "bar").timeout(5, TimeUnit.SECONDS).send().get();
            System.out.println(response.toString());`

but response doesn't receive and I haven't exceptions or errors.

**Comment by ctrimble** [comment]
I am seeing something like this as well, when attempting to put a directory that already exists.  The line that is hanging for me looks like this:

```
EtcdKeysResponse response = client.get().putDir(directory).prevExist(false).send().get();
```

etcd4j versions: 2.12.0 and 2.13.0
etcd version: 2.3.7.

**Comment by lburgazzoli** [comment]
do you mind submitting a pr with a failing test case? I'm quite busy these days

**Comment by ctrimble** [comment]
Not a problem.  I will write one up today.

**Comment by ctrimble** [comment]
A quick not about this.  It looks like etcd4j now requires Jackson 2.8.x, so that it can call readValue on java.io.DataInput objects.  My project is using Jackson 2.5.x.  I am not seeing anything in the logs about a missing method definition, but this could easily be root cause.

**Comment by ctrimble** [comment]
I cannot reproduce this from the etcd4j project.  I also looked for places that etcd4j might be swallowing exceptions about missing methods and found none.  I am going to verify that my Jackson versions are aligned and retest with my application.

**Comment by ctrimble** [comment]
Sorting out my Jackson dependencies resolved the issues I was seeing.

**Comment by lburgazzoli** [comment]
@wojtkuju can you have a look and check if jackson is the root of your issue too ? I may shade jackson so that it does not hurt other dependencies if not possible to upgrade

**Comment by joseluissanchezgracia** [comment]
The same for me. I was using jackson 2.3 in my project's pom. 
A simple
`etcd.get("key").timeout(5, TimeUnit.SECONDS).send().get();`
was not returning response with no exceptions, just locked
Using version 2.8.6 for jackson dependencies fixed the problem.

Thank you @ctrimble, you saved my day

**Comment by lburgazzoli** [comment]
I'm going to see if the missing method definition can be reported
