### ISSUE TITLE
putDir() raise Exception

### ISSUE THREAD

**Issue by wjw465150** [jurmous/etcd4j#141]
@org.junit.Test
  public void testDir() {
      try {
        client.putDir("/dir_1").send().get(); 
      } catch (EtcdException e) {
        if (e.isErrorCode(EtcdErrorCode.NotFile) == false) {
          e.printStackTrace();
        }
      } catch (Exception e) {
        e.printStackTrace();
      }
  }

**Comment by lburgazzoli** [comment]
This is because you call it i.e. twice, see the etcd behavior:

```
$ curl http://127.0.0.1:2379/v2/keys/dir_1 -XPUT -d dir=true
{"action":"set","node":{"key":"/dir_1","dir":true,"modifiedIndex":4,"createdIndex":4}}
$ curl http://127.0.0.1:2379/v2/keys/dir_1 -XPUT -d dir=true
{"errorCode":102,"message":"Not a file","cause":"/dir_1","index":4}
```

**Comment by wjw465150** [comment]
I Understand, thank you for your timely guidance!
