### ISSUE TITLE
EtcdClient Constructor does not provide multi uris

### ISSUE THREAD

**Issue by regardfs** [jurmous/etcd4j#145]
Hi, It seems that EtcdClient Constructor do not provide multi uris for connection, usually when connecting to etcd cluster , we input all cluster nodes:port, like

> client = etcd.Client(host=(('127.0.0.1', 4001), ('127.0.0.1', 4002), ('127.0.0.1', 4003)))

May your guys tell me why we could not ?

**Comment by lburgazzoli** [comment]
Please have a look at EtcdClient constructors, they support multiple uris with varargs

**Comment by regardfs** [comment]
@lburgazzoli, Hi , I am a totally java greenhand, and spent two days to startup java, then I saw a URI ...baseurl in constructors, thanks a lot !!!
