### ISSUE TITLE
Does etcd4j Etcdclient support lasting waitForChange function？

### ISSUE THREAD

**Issue by regardfs** [jurmous/etcd4j#147]
For now，I could monitor one time etcd value change and do a reaction with code below:

> EtcdResponsePromise etcdResponsePromise = etcdClient.getDir(etcdConfPrefix).recursive().waitForChange().timeout(-1, TimeUnit.SECONDS).send();

 

> etcdResponsePromise.addListener(promise -> { System.out.println("changed"); });

I want to know does etcd4j Etcdclient support lasting waitForChange function？

**Comment by lburgazzoli** [comment]
If I properly understand you want a listener for events, in that case can you have a look at: https://github.com/apache/camel/blob/master/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java

**Comment by regardfs** [comment]
@lburgazzoli , thanks a lot!!!
I mean monitor etcd key and do sth, like this cmd:**/usr/bin/etcdctl exec-watch --recursive /corekube/apiservers -- /opt/bin/echosth.sh**

**Comment by lburgazzoli** [comment]
So yes you can look at the example I provided, it use an index to avoid loosing events in between

**Comment by regardfs** [comment]
@lburgazzoli , hi
firstly, I am a new greenhand on java, I am a pythoner and goer.
I .have read all code in the link:https://github.com/apache/camel/blob/master/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java
but It seems that it still a one time event for etcdwatch.

> /usr/bin/etcdctl  exec-watch --recursive /corekube/apiservers -- /opt/bin/echosth.sh

that means watch on /corekube/apiservers  and if sth changed  it will run /opt/bin/echosth.sh and continue to watch on next modification. 

> / # etcdctl exec-watch --recursive /configurations/gaia/foo -- "1.sh"
Mon May 22 15:25:20 UTC 2017: changed
Mon May 22 15:25:26 UTC 2017: changed
Mon May 22 15:25:30 UTC 2017: changed

**Comment by lburgazzoli** [comment]
When the code starts it invokes the [watch method](https://github.com/apache/camel/blob/master/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java#L140-L153)

Then inside the callback, it [invokes watch](https://github.com/apache/camel/blob/master/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java#L134) again.

**Comment by regardfs** [comment]
@lburgazzoli 
you mean this one will start first and trigger watch() in onResponse()?

>     protected void doStart() throws Exception { 
>         super.doStart(); 
>         watch();
>     }

**Comment by lburgazzoli** [comment]
Yes


---
Luca Burgazzoli

**Comment by regardfs** [comment]
@lburgazzoli ，
Sorry for bothering u again and again, 
It seems that use start and onResponse together to generate the loop, but I could comprehend how，so dismay..

**Comment by lburgazzoli** [comment]
- doStart is just the entry point for camel
- watch then uses waithForChanges and registers onResponse as callback and sets the right index
- the onResponse, once done processing the data, calls watch again

**Comment by regardfs** [comment]
@lburgazzoli thanks a lot!!!!

**Comment by regardfs** [comment]
@lburgazzoli last question, soooooooooo appreciating you patience and explaination!
how to register onResponse?Is this one: 

> https://github.com/apache/camel/blob/3505e718db48cc0d8be5b47f6c4030c958d93a5f/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java#L153

**Comment by lburgazzoli** [comment]
Yes it is, you need to associate a callback to the promise you get

**Comment by regardfs** [comment]
@lburgazzoli hurray!!!
Thanks, I wish u merry Christmas and happy new year :)
