### ISSUE TITLE
Etcd v2 basic auth api take 40 ms to process single put request to etcd server.

### ISSUE THREAD

**Issue by suresh-chaudhari** [jurmous/etcd4j#149]
Required to update this api with v3 version with this client as etcd server has improved authorization with v3 api.

**Comment by suresh-chaudhari** [comment]
when do you have plan to upgrade?

**Comment by lburgazzoli** [comment]
No plans to support v3 here in etcd4j as it would require a complete rewrite.
There is a new official client for v3 in development: https://github.com/coreos/jetcd

**Comment by suresh-chaudhari** [comment]
is this provided https://github.com/coreos/jetcd complete development of etcd v3 api support with connection pooling mechanism?

**Comment by lburgazzoli** [comment]
For more information on jetcd you should post questions on that project, I did some small contributions in the past but I do not know how it has been evolved. 

It is based on grpc btw.
