### ISSUE TITLE
Does this etcd4j provide lock function like "etcdctl lock mylock..."

### ISSUE THREAD

**Issue by regardfs** [jurmous/etcd4j#150]
Hi, I want to figure out how do I use this package to fulfill the tasks of **distribute key lock request**, for now I use below shell scripts to handle this:

> mkfifo mylock.fifo
ETCDCTL_API=3 ./bin/etcdctl lock mylock >mylock.fifo &
pid=$!
if read lockname <mylock.fifo; then
    echo holding lock with key $lockname
    ... do whatever ...
fi
kill $pid
wait $pid

But it is not the best solution，cause My other code is all written by java and this package module，do we support this.
Thanks a lot for your feedback.

**Comment by lburgazzoli** [comment]
this client implements etcd v2 API only, for v3 there is https://github.com/coreos/jetcd
you can implement something similar to a lock using PUT with prevExist / prevValue options.

**Comment by regardfs** [comment]
@lburgazzoli Thanks a lot, I closed this issue.

**Comment by regardfs** [comment]
@lburgazzoli , hi , I meet a very st

**Comment by lburgazzoli** [comment]
Need to digg into it, can you send a PR with a failing test ?

**Comment by regardfs** [comment]
@lburgazzoli for now I do not have time to make a PR, I would like to close this issue now, and will make PR when new guys join my team and let they do this.
