### ISSUE TITLE
in memory caching using etcd4j

### ISSUE THREAD

**Issue by naveenkumargp** [jurmous/etcd4j#154]
Hi All,
i want to store the etcd data into the local cache using this etcd4j i e i want cache the etcd data using this etcd client code .is it possible to do with this present code if not how do we change the code .
can any one help to how to do this.
Regards
Naveen

**Comment by ajaygk95** [comment]
Yes this would be very helpful for applications that executes GET requests, instead of trying to get data always from etcd a cache is more faster way.. Please suggest.

**Comment by lburgazzoli** [comment]
You can use a number of caching solutions like caffeine and build your own cache store/loader on top of etcd4j.

etc4j does not have any cache and won't have one.

**Comment by naveenkumargp** [comment]
thank you lburgazzoli i will try caffiene  library module.

regards
naveen
