### ISSUE TITLE
etcd4j  supports backup

### ISSUE THREAD

**Issue by belovers** [jurmous/etcd4j#161]
i wanna know when etcd4j could support backup function?

**Comment by lburgazzoli** [comment]
what do you mean ?

**Comment by belovers** [comment]
I mean the current version of etcd4j does not support backup interface (etcd backup cmd) , when it can support?

**Comment by lburgazzoli** [comment]
There's no plan to improve etcd4j, main work around etcd java client happens on coreos/jetcd
