### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by dgutierrez-stratio** [jurmous/etcd4j#169]
Hi guys, we are very interested in a new release including features from PR #168 and PR #164. Do you have it in your nearby roadmap? Thanks!

**Comment by lburgazzoli** [comment]
I can do a release this week unless you have other PR to get included

**Comment by dgutierrez-stratio** [comment]
Hi @lburgazzoli! Sure thing, I've just extended JSON functionalities on PR #170 closely related to #168. Thanks in advance

**Comment by dgutierrez-stratio** [comment]
Thanks for merging PR #170 @lburgazzoli, we are ready for the release!

**Comment by jesusmartinez-stratio** [comment]
@lburgazzoli Thanks for merging #171 and #172 

Is there any possibility to release a new version?

Thank you!! :smile:

**Comment by dgutierrez-stratio** [comment]
Sorry to insist but, any news on the release? Thanks!

**Comment by lburgazzoli** [comment]
I did try yesterday but found some issue, will re-try today. Sorry for the delay

**Comment by lburgazzoli** [comment]
Ok I did it, 2.15.0 should be available soon on maven central

**Comment by lburgazzoli** [comment]
Let me know if you have troubles
