### ISSUE TITLE
Connecting to a etcd cluster using dns server name instead of IP

### ISSUE THREAD

**Issue by pankaj-cashify** [jurmous/etcd4j#175]
When I use DNS server name instead of IP for etcd URL. The ETCD clients either hangs for long period of time or return result after 30 seconds or so.

EtcdClient etcd = new EtcdClient(URI.create("http://etcd.prv.api.abcd.in:80"));
String value = etcd.get("test").send().get().getNode().getValue();
System.out.println("value: " + value);

Above code works fine if I use URL as http://127.0.0.1:2379

**Comment by lburgazzoli** [comment]
did you try with etcdctl ?

**Comment by pankaj-cashify** [comment]
I can run 'curl http://etcd.prv.api.abcd.in:80/v2/keys/test' fine
