### ISSUE TITLE
Timeout or connection timeout is not working.

### ISSUE THREAD

**Issue by sarvandhoot** [jurmous/etcd4j#179]
In case if ETCD is down connection is not getting timed out. 

I have used both put and get API and it waits for indefinite time for making the timeout.

I have used the version 2.15.0 and 2.16.0

Please suggest. 

-Sarvan

**Comment by sarvandhoot** [comment]
Hi,

Best of my knowledge -

This is how I am creating the client.

EtcdNettyConfig config = new EtcdNettyConfig();
config.setConnectTimeout(10);
EtcdNettyClient nettyClient = new EtcdNettyClient(config,
URI.create(etcduri));
etcdClient = new EtcdClient(nettyClient);


and

get request -

// get the ResponsePromise
// get the value from ResponsePromise
EtcdKeyGetRequest getRequest = client.get(key).timeout(1, TimeUnit.SECONDS);
try{
  return getRequest.send();
}catch(IOException e){
  try{
    // Retry again once
    return getRequest.send();
  }catch(IOException e1){
   throw e1;
  }catch(Exception e1){
  throw e1;
  }
}catch(Exception e){
throw e;
}


put request -

// put the key-value
EtcdResponsePromise<EtcdKeysResponse> promise = client.put(key,
value).timeout(1, TimeUnit.SECONDS).send();
// Call the promise in a blocking way
  try{
    EtcdKeysResponse response = promise.get();
    // Do something with response
  }catch(EtcdException e){
    if(e.isErrorCode(EtcdErrorCode.NodeExist)){
        throw new RestException("error occured");
    }
    // Do something with the exception returned by etcd
  }catch(IOException | TimeoutException e){
    throw new RestException("Timeout error");
  }

Regards,
Sarvan Kumar Dhoot
Bangalore
+91-90365 03218

**Comment by lburgazzoli** [comment]
see:
https://github.com/jurmous/etcd4j#set-a-retry-policy
https://github.com/jurmous/etcd4j#set-timeout-on-requests

**Comment by sarvandhoot** [comment]
Hi,

Is it necessary to use the retry for the timeout process. 

Thanks its working now.

**Comment by lburgazzoli** [comment]
yes it is, by default it retries indefinitively
