### ISSUE TITLE
WARN log message for all redirect

### ISSUE THREAD

**Issue by aaskey** [jurmous/etcd4j#24]
Hi there,

Seems etcd4j logs a WARN message for each redirect. This results in excessive log messages in clustering environment. It is not really a warning situation. 

Here is the message:
Jan 05 2015 15:34:41.339 [nioEventLoopGroup-6-6] [EtcdKeyResponseHandler.java:82] WARN  m.e.t.EtcdKeyResponseHandler - redirect for /v2/keys/test to http://127.0.0.1:4004/v2/keys/test

Can you please change the log level to DEBUG or no log at all for this?

Thanks,

Ken

**Comment by jurmous** [comment]
You are right. I originally made this a warning since the redirects I encountered in single node mode where all wrong and should be changed. But in cluster setups redirects can be expected in normal operation. It is now a debug log.

It is fixed in version 2.1 which has just been released.
