### ISSUE TITLE
Async / Wait operations support. 

### ISSUE THREAD

**Issue by ghristov** [jurmous/etcd4j#25]
Usually a user should be able to watch over a key / dir for a change and when there is a change the user must be notified. This is useful for dynamic application configuration changes. If i have an app which is configured via ETCD and someone decides to change a single parameter, the application must be able to recognize such event and act upon it. 

i.e. change the db host.

**Comment by jurmous** [comment]
Is there something that caused you to miss this functionality? If something in the README or code caused confusion I can improve that :)

**Comment by ghristov** [comment]
No, no the mistake is all mine. Thank you anyways ;)
