### ISSUE TITLE
reponse handler can miss response or exception

### ISSUE THREAD

**Issue by slintes** [jurmous/etcd4j#29]
since a IsSimplePromiseResponseHandler is added after a request was send, it can happen (and for us did happen very often) that the response (or exception) was already received before the handler is added. The handler is not called in this case and waits forever. PR follows.

**Comment by slintes** [comment]
see https://github.com/jurmous/etcd4j/pull/30

**Comment by jurmous** [comment]
That I never encountered this.. Thanks for reporting it!

**Comment by jurmous** [comment]
Released in 2.1.2
