### ISSUE TITLE
Default retry handler causes infinite loop

### ISSUE THREAD

**Issue by MartinPodval** [jurmous/etcd4j#31]
I use default retry handler RetryWithExponentialBackOff using -1 as maxRetryCount. Unfortunately this specific setting results into infinite loop as method RetryWithExponentialBackOff.shouldRetry returns always true in the case of maxRetryCount=-1 - first condition is always skipped.

Note that I used following statement to create the policy:

new RetryWithExponentialBackOff(20, -1, 1000)

**Comment by jurmous** [comment]
I do not understand your issue. -1 will retry indefinitely until etcd returns a valid response. Or is this issue an effect of issue #32 in which some valid responses are treated as errors?

**Comment by MartinPodval** [comment]
Ok, I understand. The problem here is that if ETCD does not working, e.g. you use wrong url, this causes infinite loop.

I mean I tried to verify behavior how my component works when it's not possible to connect to etcd, e.g. because of network partition. My test terminated in infinite loop because of described problem.

Lets say you starting your server which needs to connect to remote etcd instance during init. The server will not work and you are not able to find out what happen.

**Comment by jurmous** [comment]
It indeed causes an infinite retry loop with the default retry handler. You can change to other retry behaviors. The log will tell what is going on while retrying:

[nioEventLoopGroup-2-11] DEBUG mousio.client.retry.RetryPolicy - Retry 10 to send command
[nioEventLoopGroup-2-12] DEBUG mousio.etcd4j.transport.EtcdNettyClient - Connection failed to https://127.0.0.1:4001

What do you propose? Use a different default RetryHandler which quits after some time?

**Comment by MartinPodval** [comment]
I would suggest to break the loop if maxRetryCount either maxDelay exceeds defined limits.

**Comment by jurmous** [comment]
Oh I see what you meant now. I overlooked the 1000ms max delay. Will fix it! Thanks for reporting!
