### ISSUE TITLE
Retry handler is invoked only when a connection failed

### ISSUE THREAD

**Issue by MartinPodval** [jurmous/etcd4j#33]
I use aggressive timeouts when querying ETCD. It  often results to timeout exception.
Etcdj4 uses nice system of retry handlers.

However, according to https://github.com/jurmous/etcd4j/blob/master/src/main/java/mousio/etcd4j/transport/EtcdNettyClient.java#L167 it seems that some retry policy is performed only when promise does not succeed. Log entry in the condition says that this happen only when connection failed.

I'd appreciate to use retry handler even for timeout exception. In general, we can say that there are certain conditions when it makes sense to retry but there are also conditions when it does not make a sense to do retry. Depends on a use-case.

From my point of PUT view, I will do retries in case of timeout exception until some counter exceeds or until ETCD results precondition fails - which means that the code changes the value in ETCD but the request was timeout on client side - in fact, it succeeded but after my timeout.

This sounds exactly like an implementation of already implemented handler(s) but placed on request execution itself, not only on connection.

**Comment by jurmous** [comment]
Thanks for reporting the issue! I added a retry when there are Netty Handler failures including timeouts.

I have released version 2.3.0 which includes the fixes.
