### ISSUE TITLE
Large values are not handled

### ISSUE THREAD

**Issue by zlooo** [jurmous/etcd4j#37]
If a large value is stored etcd4j does not handle it correctly. By large I mean value grater than 8096 which causes io.netty.handler.codec.http.multipart.HttpPostRequestEncoder to create a chunked request. If that happens request without a body is sent to etcd and operation never completes.

**Comment by jurmous** [comment]
Fixed in f93fae32cad29977e352683a5eed74d40898eba1 and released in 2.4.0
