### ISSUE TITLE
Support for SRV records

### ISSUE THREAD

**Issue by OskarKjellin** [jurmous/etcd4j#41]
Etcd allows to bootstrap over SRV records and tools such as confd supports reading them. Would be nice if etcd4j could read them. This is the code that I am using the bootstrap etcd4j using SRV records (I can make a PR if you want to). 
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#dns-discovery
Does this sound like a good idea?

    private URI[] getUris(String service) throws NamingException {
        List<URI> uris = new ArrayList<>();
        String srvService = "_etcd._tcp." + service;
        Hashtable<String, String> env = new Hashtable<>();
        env.put("java.naming.factory.initial", "com.sun.jndi.dns.DnsContextFactory");
        env.put("java.naming.provider.url", "dns:");
        DirContext ctx = new InitialDirContext(env);
        Attributes attributes = ctx.getAttributes(srvService, new String[]{"SRV"});
        NamingEnumeration<? extends Attribute> records = attributes.getAll();
        while (records.hasMore()) {
            Attribute next = records.next();
            NamingEnumeration<String> values = (NamingEnumeration<String>) next.getAll();
            while (values.hasMore()) {
                String dns = values.next();
                String[] split = dns.split(" ");
                String port = split[2];
                String host = split[3];
                URI uri = URI.create("http://" + host + ":" + port);
                uris.add(uri);
            }
        }
        return uris.toArray(new URI[0]);
    }

**Comment by jurmous** [comment]
Thanks for the suggestion! 

I like the code for converting SRV records and I think those records can be a good way to manage the etcd urls.

I am only doubting a bit if this belongs to the etcd4j library. I want to keep the library small and focussed and if I add this I maybe cross the border so I may need to add more ways to configure the URIs. (Like reading in a txt file, run parameters or environment variables.)

Or do you think it should be part of the core or maybe a small utility library? I am curious for your reasons :)

**Comment by OskarKjellin** [comment]
Well, I think it should be part of the core because it is part of the etcd core (thus integrating should supporting it). Other tools that integrate with etcd do support this (like confd). 

Because it does not add any new dependencies either I would say it's OK to have it in etcd4j or do you disagree?

**Comment by jurmous** [comment]
Ah yes, I somehow forget to check the link so I missed it is also in etcd itself. That is a pretty good argument and I will now integrate the support into etcd4j. 

I will probably add a utility class to convert the DNS SRV record information to URI[] so it can be passed on to EtcdClient.

Thanks for the code and the suggestion!

**Comment by OskarKjellin** [comment]
Awesome! Looking forward to it :)

**Comment by jurmous** [comment]
What do you think of the current commit 170651a? I have added the functionality in a SRV2URIs class with both support for passing a service name to the etcd native "_etcd-server._tcp." address and passing your own complete DNS name. 

If you are ok with this commit I will base a new release on it.

**Comment by OskarKjellin** [comment]
That looks good! Confd uses _etcd._tcp which is why we use that (defined with different ports). But because we send in our own complete it looks good to me!

**Comment by jurmous** [comment]
Released in 2.6.0. Thanks!
