### ISSUE TITLE
Host header default and proxies

### ISSUE THREAD

**Issue by ctrimble** [jurmous/etcd4j#45]
Defaulting the `Host` header to the local interfaces host name may not be the best default.  When connecting to Etcd behind a proxy, the host header needs to match the host being contacted, otherwise the proxy will fail.

A better default would be to extract the host from the url being connected to.  This would allow proxies to work as expected.

**Comment by jurmous** [comment]
Thanks for reporting this issue! It is indeed more sensible to use the host name of the URI being connected to.

**Comment by ctrimble** [comment]
@jurmous, thanks for changing this.  You may want to update the README.md as well, since it specifies the default behavior.

**Comment by jurmous** [comment]
Thanks for pointing me out! I will update it when this fix will be released in the next version. This way it will not confuse people visiting the github page and working with the current version.

**Comment by jurmous** [comment]
Released in 2.7.0 and I updated the README. Thanks!
