### ISSUE TITLE
etcd4j project layout

### ISSUE THREAD

**Issue by lburgazzoli** [jurmous/etcd4j#58]
As today the project is structured as a single project even if it has two main component (source sets):
- etcd4j-client
- etcd4j

Then on maven central, there are two jars matching the source sets but:
- etcd4j contains also the classes included in etcd4j-client
- etcd4j-client is not resolvable via maven 

So I'm thinking if it would be better to convert the project to a multi project or get rid of separate etcd4j-client source set and etcd4j-client jar on maven.

Anything that make sense for you ?

**Comment by jurmous** [comment]
I think it is best to get rid of the separate client jar and make it one project again. The need to separate them was dissolved later.

**Comment by lburgazzoli** [comment]
Are you ok if I do it? I have some time to spare on etcd4j
