### ISSUE TITLE
How can I get etcd stats using etcd4j

### ISSUE THREAD

**Issue by johneke** [jurmous/etcd4j#63]
Hi @jurmous, Im sorry if this is the wrong place for this but I didnt find a room on gitter.

Is it possible to perform GET requests on non `/v2/keys` keys? I need to `GET /v2/stats/self` and I cant seem to figure out how to do that with etcd4j

I'd appreciate any pointers. Thanks a lot!

**Comment by lburgazzoli** [comment]
Stats are included in the latest code but unfortunately not yet on maven, can you check it out and test it ?

**Comment by johneke** [comment]
Great! Ill try it out now

**Comment by johneke** [comment]
It works! Thanks @lburgazzoli! Will this be making it to maven sometime soon? :)

**Comment by lburgazzoli** [comment]
It is in @jurmous hands

**Comment by jurmous** [comment]
I have published 2.8.0-SNAPSHOT. We want probably to fix the open issue before releasing 2.8.0. @lburgazzoli Any other issues withholding release?

**Comment by lburgazzoli** [comment]
Not on my side

**Comment by jurmous** [comment]
Released. @lburgazzoli If you would like to add extra notes to the release or README you are welcome.

**Comment by lburgazzoli** [comment]
I will

**Comment by johneke** [comment]
Great! Thanks guys :+1: 

Is this on the maven repos yet? README says it is but I don't see it

**Comment by jurmous** [comment]
Ah the last step failed in publish process because the source and javadoc jars are not present anymore in gradle built. I will fix that at a later moment. For now I refer to the SNAPSHOT build

**Comment by johneke** [comment]
Sounds good @jurmous, Ill use the snapshot jar for now. Would it be possible to notify me here when its published to maven? Maybe a separate issue? Or I could just keep checking maven :)

**Comment by jurmous** [comment]
@johneke I just fixed the gradle build to again push javadoc and sources jar and released 2.8.0 on maven central. :smile:

**Comment by johneke** [comment]
Works!!! Thanks @jurmous! :+1:

**Comment by jurmous** [comment]
You are welcome! And thanks to @lburgazzoli for the implementation of the feature!
