### ISSUE TITLE
Jackson Object Mapper

### ISSUE THREAD

**Issue by lburgazzoli** [jurmous/etcd4j#67]
Hi @jurmous ,

as the number of decoders is growing and write them is just a very manual task, would you mind if I switch to Jackson Object Mapper ? I know we already had this discussion but now that the messages we support is growing I think the advantages outcome the small issues it adds (dependencies, maybe slower parsing)

**Comment by jurmous** [comment]
What would be the consequence to the API? Can that be maintained to be backward compatible?

**Comment by lburgazzoli** [comment]
API won't change, if they do, I'll give up

**Comment by jurmous** [comment]
Well the decoders are indeed growing more than expected. Go ahead :)

**Comment by lburgazzoli** [comment]
ok, I'll come back soon

**Comment by jurmous** [comment]
Merged in https://github.com/jurmous/etcd4j/pull/69
