### ISSUE TITLE
whether Support persistent listener

### ISSUE THREAD

**Issue by sixinyiyu** [jurmous/etcd4j#82]

**Comment by jurmous** [comment]
Hello! What do you mean with the issue? Do you maybe need the waitForChange functionality which is already there? Or do you want it to reconnect automatically after it has an answer?

**Comment by pengyang** [comment]
hi, jurmous, etcd4j can use addListener to set a one-time listener to wait for change, but when change happened, this listener will not work any more. So, is there a persistent listener for change watching? or do you have some advice to do the same thing?

**Comment by lburgazzoli** [comment]
hi @pengyang you may have a look at Camel's [EtcdWatchConsumer](https://github.com/lburgazzoli/apache-camel/blob/CAMEL-9834/components/camel-etcd/src/main/java/org/apache/camel/component/etcd/EtcdWatchConsumer.java)

**Comment by pengyang** [comment]
lburgazzoli, thanks for your help!

**Comment by lburgazzoli** [comment]
@pengyang can we close this ?

**Comment by pengyang** [comment]
Thanks for your help. Sorry for the delay of closing issue.
