### ISSUE TITLE
getStoreStats is not working

### ISSUE THREAD

**Issue by michal-dec** [jurmous/etcd4j#83]
When I execute etcdClient.getStoreStats() - thread hangs and nothing is returned. Other requests work fine. My setup: etcd4j-2.10.0, Java 1.8_45

**Comment by jurmous** [comment]
They work here for me with etcd v2.2.5. Which etcd version do you run?

**Comment by michal-dec** [comment]
I have checked on etcd v2.2.0, v2.2.5 and v2.3. It's seems that client hangs on request getStoreStats(). Thread hangs on listeningPromise.awaitUninterruptibly(); (ResponsePromise.java:189)

**Comment by lburgazzoli** [comment]
It works for me too, can you check what etcd logs in debug mode ?

**Comment by lburgazzoli** [comment]
Closed as no feedback
