### ISSUE TITLE
Threads not closed when client is closed

### ISSUE THREAD

**Issue by JohnMurray** [jurmous/etcd4j#84]
I noticed that some threads are not closed with the ARM block. I didn't spend a lot of time figuring out where the threads are kept open, but I was able to write a very simple test and reproduce the issue on my Mac. You may need to adjust the loop counter to whatever your `ulimit` value is on your machine.

``` java
@Test public void testEtcdClientClosing() throws IOException {
    for (int i = 0; i < 10_000; i++) {
        try(EtcdClient client = new EtcdClient()) {
            client.put("test-" + i, "value-" + i).send();
            client.get("test-" + i).send();
        } // should close automatically
    }
}
```

Without fail this blows up with an `OutOfMemoryError: unable to create new native thread`.

**Comment by JohnMurray** [comment]
Just adding an update to this. My original test _did_ use the default client. I updated to use a test-utility function

```java
public class TestUtil {

    public static EtcdClient createClient() {
        return new EtcdClient(
                URI.create("http://127.0.0.1:12379"),
                URI.create("http://127.0.0.1:22379"),
                URI.create("http://127.0.0.1:32379")
        );
    }
}
```

This more accurately reflects my setup. However, the result is still the same. Also, I thought maybe not calling `get()` on the results was keeping things open waiting for the futures to resolve, but adding a `get()` to the end of each call to `send()` didn't change the outcome.

**Comment by jurmous** [comment]
Why are you creating an etcd-client within a loop 10_000 times? It is very heavy to create new Netty clients. The pools are not cleaned up that fast so you indeed run quickly out of memory. If you put the for loop within the etcd client and put gets to ensure put is done before get it runs with ease.

Is there a reason why you want to create etcd clients each time you do a request?

```
try(EtcdClient client = new EtcdClient()) {
        for (int i = 0; i < 10000; i++) {
          client.put("test-" + i, "value-" + i).send().get();
          client.get("test-" + i).send().get();
        }
      } // should close automatically
      catch (EtcdException | TimeoutException | EtcdAuthenticationException e) {
        e.printStackTrace();
      }
```
