### ISSUE TITLE
SocketException - can't assign requested address

### ISSUE THREAD

**Issue by JohnMurray** [jurmous/etcd4j#85]
I'm getting some `SocketException`s  sporadically when developing on my Mac. I can pretty reliably reproduce the issue with the following test (was testing other properties, but ended up finding this fun one)

``` java
    @Test public void testSharedClient() throws Exception{
        EtcdClient client = new EtcdClient(
            URI.create("http://127.0.0.1:12379"),
            URI.create("http://127.0.0.1:22379"),
            URI.create("http://127.0.0.1:32379")
        );
        for (int i = 0; i < 10_000; i++) {
            Thread t = new Thread(() -> {
                try {
                    client.put("test", "test").ttl(3600).send().get();
                    client.get("test").send().get();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
            t.start();
            client.put("test-2", "test-2").ttl(3600).send().get();
            t.join();
        }
    }
```

It seems it may be related to IPv6 based on the literature I can find online for this error and it does seem to be resolved by adding the following system-property. 

```
-Djava.net.preferIPv4Stack=true
```

Just thought this might be worth adding to the readme as a note / caveat / warning.

**Comment by lburgazzoli** [comment]
I'm not sure the client is fully thread safe

**Comment by JohnMurray** [comment]
@lburgazzoli I was wondering the same thing myself, although I don't think the encountered issue is related (although it may be). At any rate, it would also be worth noting that the client is _not_ thread safe in the readme.

**Comment by lburgazzoli** [comment]
I've tried to reproduce the error but I do not get it, can you post the full stack trace ?

**Comment by jurmous** [comment]
The client heavily leans on Netty for its thread safety:
https://github.com/netty/netty/wiki/New-and-noteworthy-in-4.0#well-defined-thread-model

Is there something that makes you worry about thread safety that I missed?

**Comment by lburgazzoli** [comment]
Closed as missing feedback
