### ISSUE TITLE
Refreshing key TTL

### ISSUE THREAD

**Issue by TeDDaN** [jurmous/etcd4j#90]
Since version 2.3 of etcd Time-to-Live (TTL) keys can be refreshed without notifying watchers.
The etcd4j client should support this feature.

https://github.com/coreos/etcd/releases/tag/v2.3.0

**Comment by lburgazzoli** [comment]
I will implement it soon

**Comment by TeDDaN** [comment]
I have a implementation.
A pull request is coming soon.

**Comment by TeDDaN** [comment]
Created a pull request #91 #
