### ISSUE TITLE
etcd4j can not handler auth/enable

### ISSUE THREAD

**Issue by mqingyn** [jurmous/etcd4j#94]
I implemented  PUT/DELETE /v2/auth/enable ，but EtcdResponseHandler.channelRead0 can not handler "status.equals(HttpResponseStatus.OK) && !content.isReadable()" . because auth/enable not response any content.

**Comment by lburgazzoli** [comment]
Would you be so kind to submit a PR I will take care of making it working if you can't figure it out.
