### ISSUE TITLE
EtcdNettyClient.close Issue

### ISSUE THREAD

**Issue by wangyuntao** [jurmous/etcd4j#97]
Hi guys:

When I use the custom method to construct a EtcdClient, I set my NettyEventLoopGroup to EtcdNettyConfig，But when I close EtcdClient, EtcdClient close my NettyEventLoopGroup also.

Maybe if EventLoopGroup is custom set (not the default one), EtcdClient should not close it?
Or have an option to control the behavior?

Thanks!

**Comment by lburgazzoli** [comment]
I'd say that an option - default to true - would be the way to go, something like:

```java
EtcdNettyConfig {
    boolean managedEventLoopGroup = true;

    EtcdNettyConfig setEventLoopGroup(EventLoopGroup group) {
        return setEventLoopGroup(group, true);
    }

    EtcdNettyConfig setEventLoopGroup(EventLoopGroup group, boolean managed) {
        this.eventLoopGroup = group;
        this.managedEventLoopGroup = managed;
        return this:
    }
}
```

Would you like to contribute a PR ?

**Comment by wangyuntao** [comment]
Hi, a new PR, check it!

**Comment by lburgazzoli** [comment]
I see two PR #98 and #99 and the later seems to have the same commit as the former , would you be so kind to squash the commits in one single PR ?

**Comment by wangyuntao** [comment]
Done!
